name: Code Styling
on:
  push:
    branches-ignore:
      - main
  workflow_call:
    inputs:
      php:
        description: 'PHP version'
        required: false
        type: string
        default: '8.4'
    secrets:
      COMPOSER_OAUTH_GITHUB_ACTIONS:
        required: true

jobs:
  pint:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php || '8.4' }}
          tools: composer

      - name: Install dependencies
        run: |
          composer config github-oauth.github.com ${{ secrets.COMPOSER_OAUTH_GITHUB_ACTIONS }}
          composer install --no-scripts --no-progress

      - name: Run Laravel Rector
        run: composer rector

      - name: Commit changes
        id: auto_commit_rector_action
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "[skip actions] Apply rector fixes"
          commit_user_name: GitHub Action
          commit_user_email: actions@github.com

      - name: Run Laravel Pint
        run: composer cs-fix

      - name: Commit changes
        id: auto_commit_action
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "[skip actions] Apply style fixes"
          commit_user_name: GitHub Action
          commit_user_email: actions@github.com
